catalog:
  '@antfu/ni': ^24.3.0
  '@iconify-json/carbon': ^1.2.8
  '@types/lodash-es': ^4.17.12
  '@types/node': ^22.15.15
  '@unocss/preset-legacy-compat': ^66.1.0
  '@vitejs/plugin-vue': ^5.2.3
  '@vue/runtime-core': ^3.5.13
  '@vueuse/core': ^13.1.0
  '@xiaohe01/eslint-config': ^1.5.1
  '@xiaohe01/stylelint-config': ^2.3.1
  '@xiaohe01/tsconfig': ^1.0.4
  await-to-js: ^3.0.0
  dayjs: ^1.11.13
  eslint: ^9.26.0
  esno: ^4.8.0
  husky: ^9.1.7
  lint-staged: ^15.5.2
  lodash-es: ^4.17.21
  ress: ^5.0.2
  stylelint: ^16.19.1
  terser: ^5.39.0
  typescript: ~5.8.3
  unocss: ^66.1.0
  unplugin-auto-import: ^19.2.0
  unplugin-vue-components: ^28.5.0
  vite: ^6.3.5
  vue: ^3.5.13
  vue-tsc: ^2.2.10
onlyBuiltDependencies:
  - esbuild
  - unrs-resolver